server:
  port: 8888

spring:
  config:
    activate:
      on-profile: dev

  redis:
    host: localhost
    port: 6379

  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: classpath:templates
    suffix: .html

  datasource:
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pageflow

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  security:
    oauth2:
      client:
        registration:

          naver:
            scope: profile,email
            client-name: naver
            authorization-grant-type: authorization_code
            redirect-uri: '${custom.site.client-url}/login/oauth2/code/naver'

          google:
            scope: profile, email
            client-name: google
            authorization-grant-type: authorization_code
            redirect-uri: '${custom.site.client-url}/login/oauth2/code/google'

          github:
            scope: user:email, read:user
            client-name: github
            authorization-grant-type: authorization_code
            redirect-uri: '${custom.site.client-url}/login/oauth2/code/github'


        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

logging:
  level:
    root: INFO
    org:
      pageflow: DEBUG
      springframework:
        security: INFO

custom:
  site:
    protocol: http
    base-url: '${custom.site.protocol}://localhost:${server.port}'
    client-url: '${custom.site.protocol}://localhost:3000'
    client-proxy-prefix: '/PROXY'
  auth:
  # defined in application-secret.yml
  user:
    default-profile-image-url: '${custom.site.base-url}/img/default-profile-image.png'
  email:
    from:
      no-reply: noreply@pageflow.org
      default-from-name: 페이지플로우
  admin:
    username: admin100
    password: admin100
    penname: 관리자
    email: pagefloworg@gmail.com
  file:
    web-base-url: '${custom.site.base-url}/resources/image'
    parent: /Users/sechan/local/uploads/image

dev:
  data:
    # enable, disable, according-to-ddl 중 택 1
    enabled: according-to-ddl
    random-seed: 1234
    user:
      count: 10
    book:
      count: 30
