server:
  port: 8888

spring:
  config:
    activate:
      on-profile: dev

  redis:
    host: localhost
    port: 6379

  datasource:
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pageflow

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  security:
    oauth2:
      client:
        registration:

          naver:
            scope: profile,email
            client-name: naver
            authorization-grant-type: authorization_code
            redirect-uri: '${custom.site.client-url}/login/oauth2/code/naver'

          google:
            scope: profile, email
            client-name: google
            authorization-grant-type: authorization_code
            redirect-uri: '${custom.site.client-url}/login/oauth2/code/google'

          github:
            scope: user:email, read:user
            client-name: github
            authorization-grant-type: authorization_code
            redirect-uri: '${custom.site.client-url}/login/oauth2/code/github'


        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

custom:
  site:
    base-url: 'http://localhost:${server.port}'
    client-url: 'http://localhost:3000'
    client-proxy-prefix: '/_pageflow/api'
    access-token-expire-minutes: 30
    refresh-token-expire-days: 30
  email:
    email-verify-sender: verify@pageflow.org
    no-reply-sender: no-reply@pageflow.org
  defaults:
    user-profile-img: /img/default_profile_img.png
    book-cover-img: /img/default-book-cover-img.png
  admin:
    username: admin
    password: admin
    email: pagefloworg@gmail.com
  files:
    img:
      web-url-prefix: /files/img
#      directory: C:/Users/SBS/local/uploads/img
#      directory: C:/Users/gsw05/local/uploads/img
      directory: /Users/sechan/local/uploads/img