server:
  port: 8888

spring:
  config:
    activate:
      on-profile: dev

  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: classpath:templates
    suffix: .html

  redis:
    host: localhost
    port: 6379

  datasource:
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pageflow

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  security:
    oauth2:
      client:
        registration:

          naver:
            client-name: naver
            authorization-grant-type: authorization_code
            redirect-uri: '${custom.site.base-url}/login/oauth2/code/naver'

          google:
            scope: profile, email
            client-name: google
            authorization-grant-type: authorization_code
            redirect-uri: '${custom.site.base-url}/login/oauth2/code/google'

          github:
            scope: user:email, read:user
            client-name: github
            authorization-grant-type: authorization_code
            redirect-uri: '${custom.site.base-url}/login/oauth2/code/github'


        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response


custom:
  site:
    base-url: 'http://localhost:${server.port}'
    login-form-uri: '/login'
  email:
    email-verify-sender: verify@pageflow.org
  files:
    img:
      base-url: /files/img
      directory: /Users/sechan/local/uploads/img/
