server:
  port: 8888

logging:
  level:
    root: INFO
    org:
      pageflow: DEBUG
      springframework:
        security: INFO

spring:
  config:
    import:
      - classpath:application-user.yml
      - classpath:application-book.yml
      - classpath:application-email.yml
      - classpath:application-file.yml
    activate:
      on-profile: dev

  output:
    ansi:
      enabled: always

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 15MB

  redis:
    host: localhost
    port: 6379

  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}
    url: ${DB_URL}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        type:
          preferred_uuid_jdbc_type: VARCHAR
        show_sql: true
        format_sql: true
        use_sql_comments: true

pageflow:
  site:
    protocol: http
    domain: localhost
    base-url: '${pageflow.site.protocol}://${pageflow.site.domain}:${server.port}'
    client-url: '${pageflow.site.protocol}://${pageflow.site.domain}:3000'
    client-proxy-prefix: '/PROXY'