server:
  port: 8888

spring:
  profile:
    include:
  config:
    activate:
      on-profile: dev

  output:
    ansi:
      enabled: always

  redis:
    host: localhost
    port: 6379

  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: classpath:templates
    suffix: .html

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
          enable: true

  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        type:
          preferred_uuid_jdbc_type: VARCHAR
        show_sql: true
        format_sql: true
        use_sql_comments: true

  security:
    oauth2:
      client:
        registration:

          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            scope: profile,email
            client-name: naver
            authorization-grant-type: authorization_code
            redirect-uri: '${pageflow.site.client-url}/login/oauth2/code/naver'

          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile, email
            client-name: google
            authorization-grant-type: authorization_code
            redirect-uri: '${pageflow.site.client-url}/login/oauth2/code/google'

          github:
            client-id: ${GITHUB_CLIENT_ID}
            scope: user:email, read:user
            client-name: github
            authorization-grant-type: authorization_code
            redirect-uri: '${pageflow.site.client-url}/login/oauth2/code/github'


        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

logging:
  level:
    root: INFO
    org:
      pageflow: DEBUG
      springframework:
        security: INFO

pageflow:
  site:
    protocol: http
    base-url: '${pageflow.site.protocol}://localhost:${server.port}'
    client-url: '${pageflow.site.protocol}://localhost:3000'
    client-proxy-prefix: '/PROXY'
  auth:
    jwt-secret: ${JWT_SECRET}
    access-token-expire-minutes: ${ACCESS_TOKEN_EXPIRE_MINUTES}
    refresh-token-expire-days: ${REFRESH_TOKEN_EXPIRE_DAYS}
  user:
    default-profile-image-url: '${pageflow.site.base-url}/image/default-profile-image.png'
  book:
    default-cover-image-url: '${pageflow.site.base-url}/image/default-cover-image.png'
  email:
    from:
      no-reply: noreply@pageflow.org
      default-from-name: 페이지플로우
  admin:
    username: admin100
    password: admin100
    penname: 관리자
    email: pagefloworg@gmail.com
  file:
    web-base-url: '${pageflow.site.base-url}/resources/image'
    parent: /Users/sechan/container/pageflow/image
  dev:
    data:
      # enable, disable, according-to-ddl 중 택 1
      enabled: according-to-ddl
      random-seed: 1234
      user:
        count: 10
      book:
        count: 30
